### ISSUE TITLE
Installation issues with python3

### ISSUE THREAD

**Issue by manodeep** [Maratyszcza/FPplus#2]
Thanks for writing this code-base. I am trying to install it on my laptop under `python3.6` but have run into several issues. 

The first error was from string-handling within the regexp in ``configure.py``. The error was

```python
    TypeError: cannot use a string pattern on a bytes-like object
```

I can fix that by simply adding a `decode` statement at the end of the following line:

```python
    identification = banner.splitlines()[0].decode("utf-8")
```

The next errors are: 

```python
    for m in range(mr / simd.width):
TypeError: 'float' object cannot be interpreted as an integer
```

All of these errors can be fixed by simply using the following:

```python
    from __future__ import division
    for m in range(mr // simd.width):
```

I have fixed these issues in my fork [here](https://github.com/manodeep/FPplus/commit/b350bba4be1cf1dce37f43d993c4c790ffe2f84e). Happy to send a PR if you would like.

**Comment by Maratyszcza** [comment]
Thank you, a PR would be great!
